"""empty message

Revision ID: 0c5efaa4ff16
Revises: f12727a6f411
Create Date: 2025-11-26 15:40:33.158525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5efaa4ff16'
down_revision = 'f12727a6f411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_resourse_allocation',
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('resourse_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('allocation_id')
    )
    op.create_table('resourse',
    sa.Column('resourse_id', sa.Integer(), nullable=False),
    sa.Column('resoiurse_name', sa.String(length=100), nullable=False),
    sa.Column('resourse_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('resourse_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resourse')
    op.drop_table('event_resourse_allocation')
    # ### end Alembic commands ###
