"""empty message

Revision ID: 1030cd0e0942
Revises: 0c5efaa4ff16
Create Date: 2025-11-26 20:12:13.239651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1030cd0e0942'
down_revision = '0c5efaa4ff16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resourse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resourse_name', sa.String(length=100), nullable=False))
        batch_op.drop_column('resoiurse_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resourse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resoiurse_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('resourse_name')

    # ### end Alembic commands ###
