"""empty message

Revision ID: fa4de1c91392
Revises: 1030cd0e0942
Create Date: 2025-11-26 20:27:22.513989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa4de1c91392'
down_revision = '1030cd0e0942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_resource_allocation',
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('allocation_id')
    )
    op.create_table('resource',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('resource_name', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.drop_table('resourse')
    op.drop_table('event_resourse_allocation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_resourse_allocation',
    sa.Column('allocation_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resourse_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('allocation_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('resourse',
    sa.Column('resourse_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resourse_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('resourse_name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('resourse_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('resource')
    op.drop_table('event_resource_allocation')
    # ### end Alembic commands ###
